name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-host

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./backend-fastify/Dockerfile --file Dockerfile --tag fullstack-challenge:$(date +%s)
